// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3KIYLXtqitC460AfgRGwvG6ajs133ndo',
    appId: '1:194799374366:web:912c1b7453139954841e0f',
    messagingSenderId: '194799374366',
    projectId: 'proyecto-base-de-datos-b6f45',
    authDomain: 'proyecto-base-de-datos-b6f45.firebaseapp.com',
    storageBucket: 'proyecto-base-de-datos-b6f45.appspot.com',
    measurementId: 'G-8FDSWLFV7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8DuO7u5QTKDzjLnynyR_0NTapl-kiFpA',
    appId: '1:194799374366:android:9435bc9a7b43bb41841e0f',
    messagingSenderId: '194799374366',
    projectId: 'proyecto-base-de-datos-b6f45',
    storageBucket: 'proyecto-base-de-datos-b6f45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVKa-dOhnzDrNRDNQx2jAO90_uNretVAc',
    appId: '1:194799374366:ios:33a694b1bf1ff32d841e0f',
    messagingSenderId: '194799374366',
    projectId: 'proyecto-base-de-datos-b6f45',
    storageBucket: 'proyecto-base-de-datos-b6f45.appspot.com',
    iosBundleId: 'com.example.appjared',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVKa-dOhnzDrNRDNQx2jAO90_uNretVAc',
    appId: '1:194799374366:ios:33a694b1bf1ff32d841e0f',
    messagingSenderId: '194799374366',
    projectId: 'proyecto-base-de-datos-b6f45',
    storageBucket: 'proyecto-base-de-datos-b6f45.appspot.com',
    iosBundleId: 'com.example.appjared',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3KIYLXtqitC460AfgRGwvG6ajs133ndo',
    appId: '1:194799374366:web:2740e745ba873b4f841e0f',
    messagingSenderId: '194799374366',
    projectId: 'proyecto-base-de-datos-b6f45',
    authDomain: 'proyecto-base-de-datos-b6f45.firebaseapp.com',
    storageBucket: 'proyecto-base-de-datos-b6f45.appspot.com',
    measurementId: 'G-3Z59EKC00X',
  );
}
